name: Build and push Docker image

on:
  push:
    branches:
      - '**'

jobs:
  test-admin-shell-client-server:
    runs-on: ubuntu-latest
    name: Test Admin Shell Client Server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: |
          dotnet test basyx-dotnet-tests/AdminShellClientServerTests/AdminShellClientServerTests.csproj --verbosity normal
  
  test-admin-shell-repo-client-server:
    runs-on: ubuntu-latest
    name: Test Admin Shell Repo Client Server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: |
          dotnet test basyx-dotnet-tests/AdminShellRepoClientServerTests/AdminShellRepoClientServerTests.csproj --verbosity normal

  test-registry-client-server:
    runs-on: ubuntu-latest
    name: Test Registry Client Server Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: |
          dotnet test basyx-dotnet-tests/RegistryClientServerTests/RegistryClientServerTests.csproj --verbosity normal          

  build-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build docker image
    needs: [test-admin-shell-client-server, test-admin-shell-repo-client-server, test-registry-client-server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push fluid-basyx-dotnet-repo-server image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.Repo.Server
          push: true
          tags: danielkleinemag/fluid-basyx-dotnet-repo-server:latest

      - name: Build and push fluid-basyx-dotnet-aas-sm-server image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.AASX.SM.Server
          push: true
          tags: danielkleinemag/fluid-basyx-dotnet-aas-sm-server:latest