name: Build and push Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'basyx-dotnet-tests/**'
      - '.github/workflows/aasx-sm-server-docker-image.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          tags: danielkleinemag/fluid-basyx-dotnet-aasx-server:latest
